series: Basic OpenGL with GLFW
title: Point Lighting
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Use point lights to apply more realistic shading.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: Basic OpenGL with GLFW
    title: Basic Lighting